title: "harshitha-s"
tagline: "Data Science | AI | Machine Learning"
description: "Welcome to my portfolio. Showcasing my projects, skills, and achievements in Data Science."
github_username: harshithaa14
linkedin_username: sarabudla-harshitha
